import Head from 'next/head'
// import '../styles/globals.css'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.titulo}>Ola mundo</h1>

    </div>
  )
}
